#!/usr/bin/with-contenv bash

echo "Starting rclone."

if [ ! -d "/media" ]; then
  /bin/mkdir -p "/media"
  chown plex:plex "/media"
else
  chown plex:plex "/media"
fi

exec s6-setuidgid plex /bin/sh -c '/usr/sbin/rclone --config /config/rclone.conf mount --read-only '${RCLONE_MOUNT_ARGUMENTS}' '${RCLONE_MOUNT_CONFIG}' /media'
